services:


  rocket:
    #image: gresendesa/webrocket:1.0
    build: .
    container_name: rocket
    restart: always
    ports:
      - "3001:80"
    networks:
      - macrosoft

networks:
  macrosoft:
    driver: bridge
